### PR TITLE
Merge Rubber into Elastix

### PR DESCRIPTION
**Pull request by evuez**
2 weeks ago I started a fork of Elastix (https://github.com/evuez/rubber) because I needed some functions and you didn't seem to be available at the time to merge my PR, but seeing that you merged it last week I thought I might as well merge my updates back into your repo.

I cleaned up some functions, removed some duplicated code, updated the README and started adding documentation and specs. I also added support for the `_msearch` endpoint.

I know it's a lot of updates to merge so if you want me to split that into separate PRs I can do that ;)

P.S.: The documentation for my fork is on [hexdocs](https://hexdocs.pm/rubber/) if you want to check it out to see how it looks before merging this.

### CODE REVIEW

**Comment by evuez** [comment]
@werbitzky Also if you need help maintaining this repo I'd love to help 😃

**Comment by werbitzky** [comment]
Hi @evuez sorry for the delay, long vacation. I'd like you to join the repo as a collaborator – what do you think? Cheers

**Comment by evuez** [comment]
No problem! I'll try to update this PR with my latest updates in Rubber this weekend :)

**Comment by evuez** [comment]
@werbitzky I added all my updates from rubber, could you check if everything looks good before I merge it?

I thought it would be nice to make a new release since a lot of things have been added since 0.5.0, so I updated the changelog and bumped the version in mix.exs to 0.6.0, is that ok?
It also contains the code from https://github.com/werbitzky/elastix/pull/47 since it was merged in rubber.

**Comment by werbitzky** [comment]
Thanks @evuez 👍I'll push a 0.6.0 version to hex during the next days after checking for low hanging fruits.

**Comment by evuez** [comment]
@werbitzky Would you have some time to push the 0.6.0 to hex? I've been using it in production for almost 2 weeks now and everything seemed fine :+1:

**Comment by evuez** [comment]
@werbitzky Would you have some time to push the 0.6.0 to hex? I've been using it in production for a few weeks now and everything seems fine :+1:

**Pull request merged**
