### PR TITLE
V1 allow custom headers

### LINKED ISSUE #13: Set request headers/support non-shield authorization header?
We're using elastic search on AWS which requires HMAC key signing as described here http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

This elixir library implements it (https://github.com/bryanjos/aws_auth) nicely, but not sure best way to extend HTTP module to allow for auth other than shield.  Happy to contribute if I can (and may have to fork library just to add it, if I can't find a clean way to work around), but I'm just getting my feet wet, and not sure if you have a strong preference for how it be done.  Thanks!

### PR DESCRIPTION
**Pull request by bglusman**
Closes #13 if merged, but this is my first pass at supporting custom headers/authorization...  it's working locally and existing specs pass, may try and add new specs later, but thought I'd propose it as is for reaction first.

### CODE REVIEW

**Comment by bglusman** [comment]
Just toggled PR to try rerunning specs, they passed locally but error on travis... not sure what the issue is, it just failed again.  If anyone has insight happy to fix up if it's my issue if I can figure out how to repro locally etc.

**Comment by werbitzky** [comment]
Hi @bglusman,

this looks good for me, thanks for the pull!

about the travis fail:
Elixir version 1.0 does not support the Elixir datatype ```MapSet``` yet, it is introduced in v1.1. Mix deps.get which is used to set up the travis environmment seems to throw an error because somewhere along the way it tries to use ```MapSet.new``` so there seems to be a version incompatibility between elixir 1.0 and the hex library.

Feel free to open another PR if you have spec updates at a later point.

cheers

**Comment by werbitzky** [comment]
Hi @bglusman,

I want to bring out a new release and provide a readme example for custom headers (I'll also make a few little changes and add a test)

Can you give an example of how you configure your custom headers with the new option so I can consider your usecase?

**Comment by werbitzky** [comment]
nice!

**Comment by JoshSmith** [comment]
Hey @bglusman just wanted to ping again on this.

**Comment by bglusman** [comment]
@JoshSmith sorry!  I missed previous ping...  I actually wound up using [elastic](https://github.com/radar/elastic/) instead of this as it had the aws_auth hex module already integrated and saved some work, but it would be the exact same headers those two projects use for AWS hosted elasticsearch authentication, which is a bit like shield, but HMAC based.  I don't think I ever got a working integration, and was looking around for example usage of aws_auth when I found @radar's library which worked pretty well and saved some time, and I think that was before you merged my PR in...  does that help?  Let me know if I can do anything else to help, good option for others to have, and perhaps for us too as I'd rather be using HTTPoison than HTTPotion!

**Comment by werbitzky** [comment]
@bglusman thank you, this was very helpful! Flexibility with JSON libraries is a good point also.

**Comment by werbitzky** [comment]
@bglusman btw, elastix is already using HTTPoison, which I also prefer

**Pull request merged**
